export const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const FETCH_PAGE = 'FETCH_PAGE';
export const FETCH_ITEMS_PER_PAGE = 'FETCH_ITEMS_PER_PAGE';
export const FETCH_FILTERS = 'FETCH_FILTERS';
